name: Build and Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './src/TradingApp/appsettings.json'
      env:
        Constants.ApiKey: ${{ secrets.OANDAAPIKEY }}
        Constants.AccountId: ${{ secrets.OANDAACCOUNTID }}
        EmailConfiguration.Password: ${{ secrets.EMAILPASSWORD }}

    - name: Configure AWS Credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1  
        role-to-assume: arn:aws:iam::590183753897:role/ecr-access  
        role-session-name: GitHubActions

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, tag, and push image to Amazon ECR
      run: |
        echo "Using ECR Registry URL: ${{ steps.login-ecr.outputs.registry }}"
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:1.0.0 -f ./src/TradingApp/Dockerfile ./src
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:1.0.0
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

