name: Build and Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './src/TradingApp/appsettings.json'
      env:
        Constants.ApiKey: ${{ secrets.OANDAAPIKEY }}
        Constants.AccountId: ${{ secrets.OANDAACCOUNTID }}
        EmailConfiguration.Password: ${{ secrets.EMAILPASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./src/TradingApp/Dockerfile ./src
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
